### PR TITLE
Update doge-screenshot

### LINKED ISSUE #30: Better screenshots
I cannot take a good picture/screenshots too save my life, nor can I graphic design. If someone would be so kind as to create anything better than the image on the README it would be appreciated.

### PR DESCRIPTION
**Pull request by jsonkenyon**
Closes #30

### CODE REVIEW

**Comment by gldraphael** [comment]
Here's another screenshot:

image

**Comment by Dj-Codeman** [comment]
@jsonkenyon What's the name of the theme you use ?

**Comment by Dj-Codeman** [comment]
@gldraphael Thanks too. If I ever change out the pic this is the next up !

**Comment by jsonkenyon** [comment]
> @jsonkenyon What's the name of the theme you use ?

I use oh-my-zsh, and the theme is Powerlevel10k.  I opted to do the rainbow, if I recall on the configuration of it, and the colors are pulled in from my desktop background using pywal.

**Comment by jsonkenyon** [comment]
@Dj-Codeman My screen resolution is also pretty high, so if I need to fix the screenshot res let me know I'll get another pull request in to make it more readable.

**Comment by jsonkenyon** [comment]
image

**Comment by Dj-Codeman** [comment]
@jsonkenyon that's even better! If you could pr it that'd be great I'll change it when I get back to a computer.

**Comment by Dj-Codeman** [comment]
@jsonkenyon that's even better! If you could pr it that'd be great I'll change it when I get back to a computer.

**Pull request merged**
